<?php
/**
 * FilmTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * VAF API
 *
 * Private API for VAF partners
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.16
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FilmTest Class Doc Comment
 *
 * @category    Class
 * @description Film
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FilmTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Film"
     */
    public function testFilm()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "original_title"
     */
    public function testPropertyOriginalTitle()
    {
    }

    /**
     * Test attribute "english_title"
     */
    public function testPropertyEnglishTitle()
    {
    }

    /**
     * Test attribute "film_website"
     */
    public function testPropertyFilmWebsite()
    {
    }

    /**
     * Test attribute "genre"
     */
    public function testPropertyGenre()
    {
    }

    /**
     * Test attribute "original_language"
     */
    public function testPropertyOriginalLanguage()
    {
    }

    /**
     * Test attribute "production_status"
     */
    public function testPropertyProductionStatus()
    {
    }

    /**
     * Test attribute "release"
     */
    public function testPropertyRelease()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "website_launch_date"
     */
    public function testPropertyWebsiteLaunchDate()
    {
    }

    /**
     * Test attribute "year"
     */
    public function testPropertyYear()
    {
    }

    /**
     * Test attribute "art_director"
     */
    public function testPropertyArtDirector()
    {
    }

    /**
     * Test attribute "aspect_ratio"
     */
    public function testPropertyAspectRatio()
    {
    }

    /**
     * Test attribute "available_in"
     */
    public function testPropertyAvailableIn()
    {
    }

    /**
     * Test attribute "colour"
     */
    public function testPropertyColour()
    {
    }

    /**
     * Test attribute "co_production_partners"
     */
    public function testPropertyCoProductionPartners()
    {
    }

    /**
     * Test attribute "costume"
     */
    public function testPropertyCostume()
    {
    }

    /**
     * Test attribute "editing"
     */
    public function testPropertyEditing()
    {
    }

    /**
     * Test attribute "makeup"
     */
    public function testPropertyMakeup()
    {
    }

    /**
     * Test attribute "music"
     */
    public function testPropertyMusic()
    {
    }

    /**
     * Test attribute "other_available_formats"
     */
    public function testPropertyOtherAvailableFormats()
    {
    }

    /**
     * Test attribute "other_name"
     */
    public function testPropertyOtherName()
    {
    }

    /**
     * Test attribute "other_role"
     */
    public function testPropertyOtherRole()
    {
    }

    /**
     * Test attribute "photography"
     */
    public function testPropertyPhotography()
    {
    }

    /**
     * Test attribute "release_format"
     */
    public function testPropertyReleaseFormat()
    {
    }

    /**
     * Test attribute "running_time_film"
     */
    public function testPropertyRunningTimeFilm()
    {
    }

    /**
     * Test attribute "running_time_series"
     */
    public function testPropertyRunningTimeSeries()
    {
    }

    /**
     * Test attribute "flemish_producer_text"
     */
    public function testPropertyFlemishProducerText()
    {
    }

    /**
     * Test attribute "sound"
     */
    public function testPropertySound()
    {
    }

    /**
     * Test attribute "sound_format"
     */
    public function testPropertySoundFormat()
    {
    }

    /**
     * Test attribute "supported_by"
     */
    public function testPropertySupportedBy()
    {
    }

    /**
     * Test attribute "synopsis_dutch"
     */
    public function testPropertySynopsisDutch()
    {
    }

    /**
     * Test attribute "synopsis_english"
     */
    public function testPropertySynopsisEnglish()
    {
    }

    /**
     * Test attribute "synopsis_french"
     */
    public function testPropertySynopsisFrench()
    {
    }

    /**
     * Test attribute "synopsis_is_other"
     */
    public function testPropertySynopsisIsOther()
    {
    }

    /**
     * Test attribute "tax_shelter_partners"
     */
    public function testPropertyTaxShelterPartners()
    {
    }

    /**
     * Test attribute "writers_text"
     */
    public function testPropertyWritersText()
    {
    }
}
