<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * VAF API
 *
 * Private API for VAF partners
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.16
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for assetsIdDownloadGet
     *
     * Returns binary data by asset id.
     *
     */
    public function testAssetsIdDownloadGet()
    {
    }

    /**
     * Test case for assetsIdGet
     *
     * Returns a asset by id.
     *
     */
    public function testAssetsIdGet()
    {
    }

    /**
     * Test case for filmsGet
     *
     * Returns all films.
     *
     */
    public function testFilmsGet()
    {
    }

    /**
     * Test case for filmsIdGet
     *
     * Returns a film by id.
     *
     */
    public function testFilmsIdGet()
    {
    }

    /**
     * Test case for filmsIdPostersGet
     *
     * Returns posters (assets) for a film.
     *
     */
    public function testFilmsIdPostersGet()
    {
    }

    /**
     * Test case for filmsIdStillsGet
     *
     * Returns stills (assets) for a film.
     *
     */
    public function testFilmsIdStillsGet()
    {
    }

    /**
     * Test case for rootGet
     *
     * Returns API version info.
     *
     */
    public function testRootGet()
    {
    }
}
